version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - tmpfs:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: financial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  tmpfs:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs